export const AUTH_TOKEN_LOGIN = 'auth/AUTH_TOKEN_LOGIN';
export const AUTH_FACEBOOK_LOGOUT = 'auth/AUTH_FACEBOOK_LOGOUT';
export const AUTH_FACEBOOK_REQUEST_PROFILE = 'auth/AUTH_FACEBOOK_REQUEST_PROFILE';
export const AUTH_FACEBOOK_RECEIVE_PROFILE = 'auth/AUTH_FACEBOOK_RECEIVE_PROFILE';
export const AUTH_FACEBOOK_ERROR = 'auth/AUTH_FACEBOOK_ERROR';
