export const AUTH_TOKEN_LOGIN = 'auth/TOKEN_LOGIN';
export const AUTH_FACEBOOK_LOGOUT = 'auth/FACEBOOK_LOGOUT';
export const AUTH_FACEBOOK_REQUEST_PROFILE = 'auth/FACEBOOK_REQUEST_PROFILE';
export const AUTH_FACEBOOK_RECEIVE_PROFILE = 'auth/FACEBOOK_RECEIVE_PROFILE';
export const AUTH_FACEBOOK_ERROR = 'auth/FACEBOOK_ERROR';
export const YELP_SET_CURRENT_LOCATION = 'yelp/SET_CURRENT_LOCATION';
export const YELP_SET_CURRENT_POSITION = 'yelp/SET_CURRENT_POSITION';
